server:
  name: web-api
  listener: 0.0.0.0:8089
  mode: debug
  timeout: 5
  enableWs: false
  enablePProf: false
  enableCron: false
  enableMetrics: false
  passEncryption: false

log:
  ServiceName: web-api
  Mode: console
  Encoding: plain
  Path: logs
  Level: debug
  Compress: true
  KeepDays: 3
